version: '3.2'
services:

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ${ENV_HOST_PATH:-/data/db}
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017

  app:
    image: com.smth.parsin:1.0-SNAPSHOT
    container_name: "com.smth.parsin"
    ports:
      - 8080:8080

    depends_on:
      - mongodb
    environment:
      - ECS_MONGO_HOST=mongodb
      - ECS_MONGO_PORT=27017
      - ECS_MONGO_USERNAME=$${ENV_MONGO_USERNAME:root}
      - ECS_MONGO_PASSWORD=$${ENV_MONGO_PASSWORD:pass}
      - ENABLE_CREATE_LINK=true
      - FEEDBACK_CHAT_LINK=https://t.me/feedbackRidesharingChat